config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :teams, param: :slug
  resources :users, only: [:index, :show], param: :username

  get 'about', to: 'about#index'

  namespace "my" do
    get 'account', to: 'users#edit'
    put 'account', to: 'users#update'
    patch 'account/change_password', to: 'users/change_password#update'
  end

  namespace :admin do
    get 'dashboard', to: "dashboard#index"
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :slug, uniqueness: { case_sensitive: false }

  before_validation :set_slug, only: [:create, :update]

  def to_param
    slug
  end

  private
    def set_slug
      self.slug = name.to_s.parameterize
    end 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :team

  enum role: { user: 0, admin: 1 }

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :name, presence: true
  validates :role, presence: true

  def username=(value)
    super(value&.downcase)
  end

  def to_param
    username
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    authorize :about, :index?

    add_breadcrumb "About", about_url
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admins
  before_action :set_admin_breadcrumb
  skip_before_action :set_crumbs

  private
    def authorize_admins
      redirect_to root_path and return unless current_user.admin?
    end

    def set_admin_breadcrumb
      add_breadcrumb "Admin", admin_dashboard_url
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index; end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_index_crumbs, only: [:index, :new]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    add_breadcrumb "New", new_admin_user_url
  end

  def create
    @user = User.new(user_params)
    @user.password = SecureRandom.alphanumeric(30)

    if @user.save
      redirect_to admin_users_url, flash: { success: "You've successfully created a new teammate account." }
    else
      redirect_to admin_users_url, flash: { error: "An error occurred while creating a teammate account: #{@user.errors.full_messages.to_sentence}." }      
    end
  end

  private

  def set_index_crumbs
    add_breadcrumb "Users", admin_users_url
  end

  def user_params
    params.require(:user).permit(
      :email,
      :username,
      :name,
      :role,
      :team_id
    )    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  before_action :authenticate
  before_action :set_crumbs

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def authenticate
    redirect_to login_path if current_user.nil?
  end

  def record_not_found
    render file: 'public/404.html', status: :not_found, layout: false
  end

  def set_crumbs
    add_breadcrumb "Home", root_url
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    authorize :dashboard, :index?
  end
end

app/controllers/my/users/change_password_controller.rb
class My::Users::ChangePasswordController < ApplicationController
  def update
    authorize current_user, policy_class: My::UserPolicy

    if current_user.authenticate(user_change_password_params[:old_password])
      current_user.password = user_change_password_params[:new_password]
      current_user.password_confirmation = user_change_password_params[:new_password_confirmation]

      if user_change_password_params[:new_password].blank? || user_change_password_params[:new_password_confirmation].blank?
        redirect_to my_account_url, flash: { error: "New password and new password confirmation cannot be empty." } and return
      end

      if current_user.save
        redirect_to my_account_url, flash: { success: "Password was successfully changed." }
      else
        redirect_to my_account_url, flash: { error: "New password and new password confirmation do no match." }
      end
    else
      redirect_to my_account_url, flash: { error: "Old password does not match the current password." }
    end
  end

  private
    def user_change_password_params
      params.require(:user).permit(
        :old_password,
        :new_password,
        :new_password_confirmation
      )
    end
end

app/controllers/my/users_controller.rb
class My::UsersController < ApplicationController
  def edit
    authorize current_user, policy_class: My::UserPolicy

    add_breadcrumb "Edit Account", my_account_url
  end

  def update
    authorize current_user, policy_class: My::UserPolicy

    if current_user.update(user_params)
      redirect_to my_account_url, flash: { success: "You've successfully updated your account." }
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :team_id
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]
  skip_after_action :verify_authorized, only: [:new, :create]

  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:error] = "Email or password is invalid"
      redirect_to login_url
    end
  end

  def destroy
    authorize :session, :destroy?

    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_index_crumbs, only: [:index, :show]

  def index
    @teams = Team.joins(:users)
  end

  def show
    @team = Team.find_by(slug: params[:slug])

    raise ActiveRecord::RecordNotFound if @team.nil?

    add_breadcrumb @team.name, team_url(@team)
  end

  private

  def set_index_crumbs
    add_breadcrumb "Teams", teams_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_index_crumbs

  def index
    authorize User

    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])

    authorize @user

    add_breadcrumb @user.username, user_url(@user)
  end

  private

  def set_index_crumbs
    add_breadcrumb "Teammates", users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message_classes_for_alert_level(value)
    case value
    when 'notice' then "blue bg-washed-blue"
    when 'success' then "green bg-washed-green"
    when 'error' then "red bg-washed-red"
    when 'alert' then "gold bg-washed-yellow"
    end
  end
end

app/views/about/index.html.erb
<header class="tc pv4 pv4-ns">
  <h1 class="f5 f2-ns fw6 mid-gray">About</h1>
</header>

<section class="mb5">
  <p class="lh-copy">
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
    vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
    no sea takimata sanctus est Lorem ipsum dolor sit amet.
  </p>
</section>

app/views/admin/dashboard/index.html.erb
Hello, Admin! :)

app/views/admin/users/index.html.erb
<header class="tc pv4 pv4-ns">
  <h1 class="f5 f2-ns fw6 mid-gray">Teammates</h1>
</header>

<%= link_to "Add new", new_admin_user_path %>


<% @users.each do |user| %>
  <ul class="list pl0 mt0">
    <li
      class="flex items-center lh-copy pa3 ph0-l bb b--black-10">
        <img class="w2 h2 w3-ns h3-ns br-100" src="http://tachyons.io/img/avatar-mrmrs.jpg" />
        <div class="pl3 flex-auto">
          <span class="f5 db black-70"><%= link_to user.name, user_url(user) %></span>
        </div>
        <div>
          <%= mail_to user.email, user.email, class: "f6 link blue hover-dark-gray" %>
        </div>
    </li>
  </ul>
<% end %>

app/views/admin/users/new.html.erb
<header class="tc pv4 pv4-ns">
  <h1 class="f5 f2-ns fw6 mid-gray">New teammate</h1>
</header>

<%= form_with model: [:admin, @user], class: "black-80" do |form| %>
  <div class="mb3">
      <%= form.label :email, class: "f6 b db mb2" %>
      <%= form.text_field :email, class: "input-reset ba b--black-20 br2 pa2 mb2 db w-100" %>

      <div class="mb3">
        <%= form.label :team, class: "f6 b db mb2" %>
        <%= form.select :team_id, options_for_select(Team.all.sort_by(&:name).map { |t| [t.name, t.id] }, form.object.team_id), { include_blank: "Choose Team" }, { class: "input-reset ba b--black-20 bg-white pointer br2 pa2 mb2 db w-100" } %>
      </div>

      <div class="mb3">
        <%= form.label :name, class: "f6 b db mb2" %>
        <%= form.text_field :name, class: "input-reset ba b--black-20 br2 pa2 mb2 db w-100" %>
      </div>

      <div class="mb3">
        <%= form.label :username, class: "f6 b db mb2" %>
        <%= form.text_field :username, class: "input-reset ba b--black-20 br2 pa2 mb2 db w-100" %>
      </div>
    </div>
    <div class="tr">
      <%= form.submit "Let's go!", class: "b ph3 pv2 input-reset ba white bg-dark-blue br3 grow pointer f6 dib" %>
    </div>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="measure center tc">
  <h1 class="display-4">Hello from Crew App!</h1>
  <p class="lead">Hope you have a nice <%= Date.current.strftime("%A") %>, <%= current_user.name %>. :)</p>

  <%= image_tag "hero-landing.png" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? %>
      <%= render 'shared/nav' %>
    <% end %>

    <main class="pa4 black-80 mw7 center">
      <%= render 'shared/flash_message' %>
      <%= render 'shared/crumbs' unless request.original_url.in?([root_url, login_url]) %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/my/users/edit.html.erb
<header class="tc pv4 pv4-ns">
  <h1 class="f5 f2-ns fw6 mid-gray">Account</h1>
</header>

<div class="measure center mb5">
  <h2 class="pb3 mb4 bb b--black-20">Details</h2>

  <%= form_with(model: current_user, url: my_account_url, method: 'put', class: "black-80" ) do |form| %>
    <div class="mb3">
      <%= form.label :name, class: "f6 b db mb2" %>
      <%= form.text_field :name, class: "input-reset ba b--black-20 br2 pa2 mb2 db w-100" %>
    </div>

    <div class="mb3">
      <%= form.label :team, class: "f6 b db mb2" %>
      <%= form.select :team_id, options_for_select(Team.all.sort_by(&:name).map { |t| [t.name, t.id] }, form.object.team_id), { include_blank: "Choose Team" }, { class: "input-reset ba b--black-20 bg-white pointer br2 pa2 mb2 db w-100" } %>
    </div>

    <div class="tr">
      <%= form.submit "Update", class: "b ph3 pv2 input-reset ba white bg-dark-blue br3 pointer f6 dib" %>
    </div>
  <% end %>
</div>

<div class="measure center">
  <h2 class="pb3 mb4 bb b--black-20">Change Password</h2>

  <%= form_with(model: current_user, url: my_account_change_password_url, method: 'patch', class: "black-80" ) do |form| %>
    <div class="mb3">
      <%= form.label :old_password, class: "f6 b db mb2" %>
      <%= form.password_field :old_password, class: "input-reset ba b--black-20 br2 pa2 mb2 db w-100" %>
    </div>

    <div class="mb3">
      <%= form.label :new_password, class: "f6 b db mb2" %>
      <%= form.password_field :new_password, class: "input-reset ba b--black-20 br2 pa2 mb2 db w-100" %>
    </div>

    <div class="mb3">
      <%= form.label :new_password_confirmation, class: "f6 b db mb2" %>
      <%= form.password_field :new_password_confirmation, class: "input-reset ba b--black-20 br2 pa2 mb2 db w-100" %>
    </div>

    <div class="tr">
      <%= form.submit "Update Password", class: "b ph3 pv2 input-reset ba white bg-dark-blue br3 pointer f6 dib" %>
    </div>
  <% end %>
</div>

<div class="measure center tr mt5">
  <%= button_to 'Logout', logout_url, method: 'delete', class: "b ph3 pv2 input-reset ba white bg-gray br3 pointer f6 dib" %>
</div>

app/views/shared/_crumbs.html.erb
<div class="w-100 tc">
  <%= render_breadcrumbs separator: ' / ' %>
</div>

app/views/shared/_flash_message.html.erb
<% if flash.any? %>
  <div class="mb3">
    <% flash.each do |key, value| %>
      <div class="w-100 ba br2 pa3 <%= flash_message_classes_for_alert_level(key) %>" role="alert">
        <%= value %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="db dt-l w-100 border-box pa3 ph5-l">
  <%= link_to root_url, class: "db dtc-l v-mid mid-gray tc tl-l mb2 mb0-l", title: "Home" do %>
    <%= image_tag "earth.png", class: "dib w2 h2 br-100", alt: "Site Name" %>
  <% end %>
  <div class="db dtc-l v-mid w-100 w-75-l tc tr-l">
    <%= link_to 'Home', root_url, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l" %>
    <%= link_to 'About', about_url, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l" %>
    <%= link_to 'News', root_url, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l" %>
    <%= link_to 'Teammates', users_url, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l" %>
    <%= link_to 'Teams', teams_url, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l" %>
    <%= link_to 'Account', my_account_url, class: "link dim dark-gray f6 f5-l dib" %>

    <% if current_user.admin? %>
      <%= link_to 'Admin Dashboard', admin_dashboard_url, class: "link dim dark-gray f6 f5-l dib ml3 ml4-l" %>
    <% end %>
  </div>
</nav>

app/views/users/index.html.erb
<header class="tc pv4 pv4-ns">
  <h1 class="f5 f2-ns fw6 mid-gray">Teammates</h1>
</header>

<% @users.each do |user| %>
  <ul class="list pl0 mt0">
    <li
      class="flex items-center lh-copy pa3 ph0-l bb b--black-10">
        <img class="w2 h2 w3-ns h3-ns br-100" src="http://tachyons.io/img/avatar-mrmrs.jpg" />
        <div class="pl3 flex-auto">
          <span class="f5 db black-70"><%= link_to user.name, user_url(user) %></span>
        </div>
        <div>
          <%= mail_to user.email, user.email, class: "f6 link blue hover-dark-gray" %>
        </div>
    </li>
  </ul>
<% end %>

app/views/users/show.html.erb
<header class="tc pv4 pv4-ns">
  <img class="w2 h2 w3-ns h3-ns br-100" src="http://tachyons.io/img/avatar-mrmrs.jpg" />
  <h1 class="f5 f2-ns fw6 mid-gray"><%= @user.name %></h1>
</header>

<ul>
  <li>Info</li>
  <li>Short Description</li>
  <li>Skills</li>
  <li>Team</li>
</ul>